# Generated by Django 5.2.6 on 2026-08-20 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_stock_image_alter_customuser_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('balance_to_profit', 'Balance to Profit'), ('profit_to_balance', 'Profit to Balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text="User's balance immediately after this transfer", max_digits=20)),
                ('profit_after', models.DecimalField(decimal_places=2, help_text="User's profit immediately after this transfer", max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer History',
                'ordering': ['-created_at'],
            },
        ),
    ]
